# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: TRANCHY TECH
email: info@tranchy.tech
description: >- # this means to ignore newlines until "baseurl:"
  tranchy.tech is a mission-driven company, focused on our guiding principles to create and development products to enhance life quality of humans.
  As we work toward our mission, we prioritize creating a community where anyone can ask and find quality answers to their issues from experts in any field. You can also get personalized, one-on-one help with your questions quickly from the people who know best.
  Besides that, we also provide intelligent solutions that solve business challenges and deliver successfully the needs of our partners.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tranchy.tech" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tranchy.tech
github_username: tranchy.tech

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

team_members:
  - name: "Tau. Dang"
    avatar: "assets/images/users/avatar-tau.png"
    role: "Developer"
  - name: "Vu. Lang"
    avatar: "assets/images/users/avatar-vu.png"
    role: "Developer"
  - name: "Vui. Nguyen"
    avatar: "assets/images/users/avatar-vui.png"
    role: "QC/QA"
  - name: "Tram. Ha"
    avatar: "assets/images/users/avatar-tram.png"
    role: "Business Analyst"
  - name: "Hieu. Doan"
    avatar: "assets/images/users/avatar-hieu.png"
    role: "Product Designer"

tranchy_one_values:
  - value: "Reliability"
    description: "Experts and businesses are curated with international evaluation standards"
    icon: "ri-service-line"

  - value: "Privacy & Security"
    description: "Protecting privacy for conversations as well as your identity"
    icon: "ri-shield-check-line"

  - value: "Fast Delivery"
    description: "Filter and send your questions to experts as quickly as possible thanks to optimal algorithms"
    icon: "ri-speed-line"

  - value: "Valuable"
    description: "Search for different opinions from all tranchy one users"
    icon: "ri-medal-2-line"

  - value: "Flexible cost"
    description: "Provide various options for the form and level of cost payment for each request"
    icon: "ri-bank-card-2-line"

  - value: "AI Assistant"
    description: "An intelligent assistant with self-learning and evolving capabilities as it accompanies you over time"
    icon: "ri-robot-line"
